.TH FREEBSD-UPDATE-NOTIFY 8
.SH NAME    \" Section header
.PP
 
freebsd-update-notify - Desktop notification for available updates

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
/usr/local/libexec/freebsd-update-notify
.ad
.fi

\" Optional sections
.SH "DESCRIPTION"

.B freebsd-update-notify
is a script, normally run by cron(8), that checks for available
base system updates (downloaded by freebsd-update(8)) and for elapsed
time since the last successful updates performed by
auto-update-system(8).

If updates have been downloaded by freebsd-update cron, or sufficient
time has elapsed since the last successful auto-update-system (according
to the "max-days-between-updates" in
etc/freebsd-update-notify/freebsd-update-notify.conf), a popup
message is displayed on the console asking the user if they would like
to perform updates.

If the user clicks "Yes", then
.B auto-update-system --defaults
is run, to update installed packages, ports, and the base system.

If the user clicks "No", the time is recorded to
/usr/local/etc/freebsd-update-notify/last-reminder, and the next
notification will occur in the number of hours specified in
the "hours-between-reminders" entry in
/usr/local/etc/freebsd-update-notify/freebsd-update-notify.conf.

.SH FILES
.nf
.na
/usr/local/etc/freebsd-update-notify/freebsd-update-notify.conf
/usr/local/etc/freebsd-update-notify/cron.d/freebsd-update-notify
.ad
.fi

.SH "SEE ALSO"
freebsd-update(8), auto-update-system(8), auto-admin(8)

.SH BUGS
The current implementation (a shell script using zenity) has limitations.
For example, there is no way to disable keyboard input, so if a notification
window pops up and grabs the keyboard while the user is typing an email,
the user may inadvertently answer the dialog with a random keystroke.
The best solution to this problem is reimplementing freebsd-update-notify
as a standalone X11 app with full input control.

Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
